Webpack commit
htmlacademy-ecmascript/1176185-cinemaddict-15 pull request #2
Opened 2021-08-08 16:21 UTC by Ferrayd

Настроил сборку вебпак.

2021-08-08 20:20 UTC, iksah requested changes

2021-08-08 20:20 UTC, iksah commented on package.json
> +    "webpack-cli": "^3.3.12"
Давай зафиксируем версии в соответствии с https://up.htmlacademy.ru/ecmascript/15/criteries#b19

2021-08-08 20:20 UTC, iksah commented on .gitignore
> +public/bundle.js.map
Добавь пожалуйста пустую строку в конце файла - иначе линтер ругается

2021-08-08 20:20 UTC, iksah commented on webpack.config.js
> +};
Добавь пожалуйста пустую строку в конце файла - иначе линтер ругается

2021-08-09 10:57 UTC, Ferrayd commented
Вроде поменял версии, только немного недопонимаю как зависит от флагов и что они означают, я так понял тут нужно было устанавливать с флагом -Е, про флаг -D и --save-dev вроде нашел информацию, а с -Е проблема.

2021-08-09 18:48 UTC, iksah commented
@Ferrayd 
> Вроде поменял версии, только немного недопонимаю как зависит от флагов и что они означают, я так понял тут нужно было устанавливать с флагом -Е, про флаг -D и --save-dev вроде нашел информацию, а с -Е проблема.

Все верно, нужно использовать флаг -E или руками удалить модификаторы версий.
При версионировании обычно используется [semver](https://semver.org/lang/ru/) - пакету присваивается трех-значный код X.Y.Z, где:

- Z - номер патча - исправления, которые закрывают баги
- Y - номер минорной версии - новая функциональность, которая не затрагивает старую
- X - номер мажорной версии - не совместимые с прошлой мажорной версией изменения

Подразумевается, что можно спокойно обновлять пакеты, пока это патчи или минорные изменения, и поэтому по умолчанию npm проставляет перед версией `^` - знак того, что подойдут любые минорные версии после указаной.
По критериям академии нам такое не подходит, и поэтому и правда нужно использовать флаг -E или --save-exact (и зафиксировать указанную версию)

-D и --save-dev - добавить зависимость в package.json как devDependencies (а значит применяться будет только в процессе разработки)

Если что, вот тут все описано https://docs.npmjs.com/cli/v7/commands/npm-install - правда на английском.
И поэтому вопрос -тебе подойдут материалы на английском, или лучше присылать на русском?

2021-08-09 18:49 UTC, merged